### ISSUE TITLE
add examples of projects that complete the entire checklist

### ISSUE THREAD

**Issue by amilajack** [amilajack/project-checklist#4]
Example:

#### React
* Initial Presentation
  - [x] Lists basic usage
* Value Proposition
  - [x] Declarative, efficient, easy to use
* Value Proposition
  - [x] Declarative, efficient, easy to use
...etc
